//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WCF.Labb1_6_1Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Labb1_6_1Service.Labb1_6_1ServiceSoap")]
    public interface Labb1_6_1ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Labb1WCF.Labb1_6_1Service.HelloWorldResponse HelloWorld(Labb1WCF.Labb1_6_1Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_1Service.HelloWorldResponse> HelloWorldAsync(Labb1WCF.Labb1_6_1Service.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        Labb1WCF.Labb1_6_1Service.GetPersonResponse GetPerson(Labb1WCF.Labb1_6_1Service.GetPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_1Service.GetPersonResponse> GetPersonAsync(Labb1WCF.Labb1_6_1Service.GetPersonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_1Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Labb1WCF.Labb1_6_1Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_1Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Labb1WCF.Labb1_6_1Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPerson", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_1Service.GetPersonRequestBody Body;
        
        public GetPersonRequest() {
        }
        
        public GetPersonRequest(Labb1WCF.Labb1_6_1Service.GetPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public GetPersonRequestBody() {
        }
        
        public GetPersonRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_1Service.GetPersonResponseBody Body;
        
        public GetPersonResponse() {
        }
        
        public GetPersonResponse(Labb1WCF.Labb1_6_1Service.GetPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Labb1WCF.Labb1_6_1Service.ArrayOfString GetPersonResult;
        
        public GetPersonResponseBody() {
        }
        
        public GetPersonResponseBody(Labb1WCF.Labb1_6_1Service.ArrayOfString GetPersonResult) {
            this.GetPersonResult = GetPersonResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Labb1_6_1ServiceSoapChannel : Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Labb1_6_1ServiceSoapClient : System.ServiceModel.ClientBase<Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap>, Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap {
        
        public Labb1_6_1ServiceSoapClient() {
        }
        
        public Labb1_6_1ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Labb1_6_1ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_6_1ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_6_1ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_6_1Service.HelloWorldResponse Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap.HelloWorld(Labb1WCF.Labb1_6_1Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Labb1WCF.Labb1_6_1Service.HelloWorldRequest inValue = new Labb1WCF.Labb1_6_1Service.HelloWorldRequest();
            inValue.Body = new Labb1WCF.Labb1_6_1Service.HelloWorldRequestBody();
            Labb1WCF.Labb1_6_1Service.HelloWorldResponse retVal = ((Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_1Service.HelloWorldResponse> Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap.HelloWorldAsync(Labb1WCF.Labb1_6_1Service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_6_1Service.HelloWorldResponse> HelloWorldAsync() {
            Labb1WCF.Labb1_6_1Service.HelloWorldRequest inValue = new Labb1WCF.Labb1_6_1Service.HelloWorldRequest();
            inValue.Body = new Labb1WCF.Labb1_6_1Service.HelloWorldRequestBody();
            return ((Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_6_1Service.GetPersonResponse Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap.GetPerson(Labb1WCF.Labb1_6_1Service.GetPersonRequest request) {
            return base.Channel.GetPerson(request);
        }
        
        public Labb1WCF.Labb1_6_1Service.ArrayOfString GetPerson(string search) {
            Labb1WCF.Labb1_6_1Service.GetPersonRequest inValue = new Labb1WCF.Labb1_6_1Service.GetPersonRequest();
            inValue.Body = new Labb1WCF.Labb1_6_1Service.GetPersonRequestBody();
            inValue.Body.search = search;
            Labb1WCF.Labb1_6_1Service.GetPersonResponse retVal = ((Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap)(this)).GetPerson(inValue);
            return retVal.Body.GetPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_1Service.GetPersonResponse> Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap.GetPersonAsync(Labb1WCF.Labb1_6_1Service.GetPersonRequest request) {
            return base.Channel.GetPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_6_1Service.GetPersonResponse> GetPersonAsync(string search) {
            Labb1WCF.Labb1_6_1Service.GetPersonRequest inValue = new Labb1WCF.Labb1_6_1Service.GetPersonRequest();
            inValue.Body = new Labb1WCF.Labb1_6_1Service.GetPersonRequestBody();
            inValue.Body.search = search;
            return ((Labb1WCF.Labb1_6_1Service.Labb1_6_1ServiceSoap)(this)).GetPersonAsync(inValue);
        }
    }
}
