//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WCF.Labb1_5ServiceGetDateByName {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap")]
    public interface Labb1_5ServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateOfNamesDay", ReplyAction="*")]
        Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponse GetDateOfNamesDay(Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateOfNamesDay", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponse> GetDateOfNamesDayAsync(Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateOfNamesDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateOfNamesDay", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequestBody Body;
        
        public GetDateOfNamesDayRequest() {
        }
        
        public GetDateOfNamesDayRequest(Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateOfNamesDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetDateOfNamesDayRequestBody() {
        }
        
        public GetDateOfNamesDayRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateOfNamesDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateOfNamesDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponseBody Body;
        
        public GetDateOfNamesDayResponse() {
        }
        
        public GetDateOfNamesDayResponse(Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateOfNamesDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDateOfNamesDayResult;
        
        public GetDateOfNamesDayResponseBody() {
        }
        
        public GetDateOfNamesDayResponseBody(string GetDateOfNamesDayResult) {
            this.GetDateOfNamesDayResult = GetDateOfNamesDayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Labb1_5ServiceSoapChannel : Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Labb1_5ServiceSoapClient : System.ServiceModel.ClientBase<Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap>, Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap {
        
        public Labb1_5ServiceSoapClient() {
        }
        
        public Labb1_5ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Labb1_5ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_5ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_5ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponse Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap.GetDateOfNamesDay(Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest request) {
            return base.Channel.GetDateOfNamesDay(request);
        }
        
        public string GetDateOfNamesDay(string name) {
            Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest inValue = new Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest();
            inValue.Body = new Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequestBody();
            inValue.Body.name = name;
            Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponse retVal = ((Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap)(this)).GetDateOfNamesDay(inValue);
            return retVal.Body.GetDateOfNamesDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponse> Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap.GetDateOfNamesDayAsync(Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest request) {
            return base.Channel.GetDateOfNamesDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayResponse> GetDateOfNamesDayAsync(string name) {
            Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest inValue = new Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequest();
            inValue.Body = new Labb1WCF.Labb1_5ServiceGetDateByName.GetDateOfNamesDayRequestBody();
            inValue.Body.name = name;
            return ((Labb1WCF.Labb1_5ServiceGetDateByName.Labb1_5ServiceSoap)(this)).GetDateOfNamesDayAsync(inValue);
        }
    }
}
