//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WCF.Labb1_6_2_Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Labb1_6_2_Service.Labb6_2Soap")]
    public interface Labb6_2Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Labb1WCF.Labb1_6_2_Service.HelloWorldResponse HelloWorld(Labb1WCF.Labb1_6_2_Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_2_Service.HelloWorldResponse> HelloWorldAsync(Labb1WCF.Labb1_6_2_Service.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name search from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        Labb1WCF.Labb1_6_2_Service.GetCountriesResponse GetCountries(Labb1WCF.Labb1_6_2_Service.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_2_Service.GetCountriesResponse> GetCountriesAsync(Labb1WCF.Labb1_6_2_Service.GetCountriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_2_Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Labb1WCF.Labb1_6_2_Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_2_Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Labb1WCF.Labb1_6_2_Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_2_Service.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(Labb1WCF.Labb1_6_2_Service.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string search;
        
        public GetCountriesRequestBody() {
        }
        
        public GetCountriesRequestBody(string search) {
            this.search = search;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_6_2_Service.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(Labb1WCF.Labb1_6_2_Service.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Labb1WCF.Labb1_6_2_Service.ArrayOfString GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(Labb1WCF.Labb1_6_2_Service.ArrayOfString GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Labb6_2SoapChannel : Labb1WCF.Labb1_6_2_Service.Labb6_2Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Labb6_2SoapClient : System.ServiceModel.ClientBase<Labb1WCF.Labb1_6_2_Service.Labb6_2Soap>, Labb1WCF.Labb1_6_2_Service.Labb6_2Soap {
        
        public Labb6_2SoapClient() {
        }
        
        public Labb6_2SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Labb6_2SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb6_2SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb6_2SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_6_2_Service.HelloWorldResponse Labb1WCF.Labb1_6_2_Service.Labb6_2Soap.HelloWorld(Labb1WCF.Labb1_6_2_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Labb1WCF.Labb1_6_2_Service.HelloWorldRequest inValue = new Labb1WCF.Labb1_6_2_Service.HelloWorldRequest();
            inValue.Body = new Labb1WCF.Labb1_6_2_Service.HelloWorldRequestBody();
            Labb1WCF.Labb1_6_2_Service.HelloWorldResponse retVal = ((Labb1WCF.Labb1_6_2_Service.Labb6_2Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_2_Service.HelloWorldResponse> Labb1WCF.Labb1_6_2_Service.Labb6_2Soap.HelloWorldAsync(Labb1WCF.Labb1_6_2_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_6_2_Service.HelloWorldResponse> HelloWorldAsync() {
            Labb1WCF.Labb1_6_2_Service.HelloWorldRequest inValue = new Labb1WCF.Labb1_6_2_Service.HelloWorldRequest();
            inValue.Body = new Labb1WCF.Labb1_6_2_Service.HelloWorldRequestBody();
            return ((Labb1WCF.Labb1_6_2_Service.Labb6_2Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_6_2_Service.GetCountriesResponse Labb1WCF.Labb1_6_2_Service.Labb6_2Soap.GetCountries(Labb1WCF.Labb1_6_2_Service.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public Labb1WCF.Labb1_6_2_Service.ArrayOfString GetCountries(string search) {
            Labb1WCF.Labb1_6_2_Service.GetCountriesRequest inValue = new Labb1WCF.Labb1_6_2_Service.GetCountriesRequest();
            inValue.Body = new Labb1WCF.Labb1_6_2_Service.GetCountriesRequestBody();
            inValue.Body.search = search;
            Labb1WCF.Labb1_6_2_Service.GetCountriesResponse retVal = ((Labb1WCF.Labb1_6_2_Service.Labb6_2Soap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_6_2_Service.GetCountriesResponse> Labb1WCF.Labb1_6_2_Service.Labb6_2Soap.GetCountriesAsync(Labb1WCF.Labb1_6_2_Service.GetCountriesRequest request) {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_6_2_Service.GetCountriesResponse> GetCountriesAsync(string search) {
            Labb1WCF.Labb1_6_2_Service.GetCountriesRequest inValue = new Labb1WCF.Labb1_6_2_Service.GetCountriesRequest();
            inValue.Body = new Labb1WCF.Labb1_6_2_Service.GetCountriesRequestBody();
            inValue.Body.search = search;
            return ((Labb1WCF.Labb1_6_2_Service.Labb6_2Soap)(this)).GetCountriesAsync(inValue);
        }
    }
}
