//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WCF.Labb1_5Reff_2_service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Labb1_5Reff_2_service.Labb1_5ServiceSoap")]
    public interface Labb1_5ServiceSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateOfNamesDay", ReplyAction="*")]
        Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponse GetDateOfNamesDay(Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDateOfNamesDay", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponse> GetDateOfNamesDayAsync(Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDatesOfNamesDay", ReplyAction="*")]
        Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponse GetDatesOfNamesDay(Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDatesOfNamesDay", ReplyAction="*")]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponse> GetDatesOfNamesDayAsync(Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateOfNamesDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateOfNamesDay", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequestBody Body;
        
        public GetDateOfNamesDayRequest() {
        }
        
        public GetDateOfNamesDayRequest(Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateOfNamesDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetDateOfNamesDayRequestBody() {
        }
        
        public GetDateOfNamesDayRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateOfNamesDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateOfNamesDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponseBody Body;
        
        public GetDateOfNamesDayResponse() {
        }
        
        public GetDateOfNamesDayResponse(Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDateOfNamesDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Labb1WCF.Labb1_5Reff_2_service.ArrayOfString GetDateOfNamesDayResult;
        
        public GetDateOfNamesDayResponseBody() {
        }
        
        public GetDateOfNamesDayResponseBody(Labb1WCF.Labb1_5Reff_2_service.ArrayOfString GetDateOfNamesDayResult) {
            this.GetDateOfNamesDayResult = GetDateOfNamesDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatesOfNamesDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatesOfNamesDay", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequestBody Body;
        
        public GetDatesOfNamesDayRequest() {
        }
        
        public GetDatesOfNamesDayRequest(Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDatesOfNamesDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetDatesOfNamesDayRequestBody() {
        }
        
        public GetDatesOfNamesDayRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatesOfNamesDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatesOfNamesDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponseBody Body;
        
        public GetDatesOfNamesDayResponse() {
        }
        
        public GetDatesOfNamesDayResponse(Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDatesOfNamesDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Labb1WCF.Labb1_5Reff_2_service.ArrayOfString GetDatesOfNamesDayResult;
        
        public GetDatesOfNamesDayResponseBody() {
        }
        
        public GetDatesOfNamesDayResponseBody(Labb1WCF.Labb1_5Reff_2_service.ArrayOfString GetDatesOfNamesDayResult) {
            this.GetDatesOfNamesDayResult = GetDatesOfNamesDayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Labb1_5ServiceSoapChannel : Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Labb1_5ServiceSoapClient : System.ServiceModel.ClientBase<Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap>, Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap {
        
        public Labb1_5ServiceSoapClient() {
        }
        
        public Labb1_5ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Labb1_5ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_5ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_5ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponse Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap.GetDateOfNamesDay(Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest request) {
            return base.Channel.GetDateOfNamesDay(request);
        }
        
        public Labb1WCF.Labb1_5Reff_2_service.ArrayOfString GetDateOfNamesDay(string name) {
            Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest inValue = new Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest();
            inValue.Body = new Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequestBody();
            inValue.Body.name = name;
            Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponse retVal = ((Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap)(this)).GetDateOfNamesDay(inValue);
            return retVal.Body.GetDateOfNamesDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponse> Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap.GetDateOfNamesDayAsync(Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest request) {
            return base.Channel.GetDateOfNamesDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayResponse> GetDateOfNamesDayAsync(string name) {
            Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest inValue = new Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequest();
            inValue.Body = new Labb1WCF.Labb1_5Reff_2_service.GetDateOfNamesDayRequestBody();
            inValue.Body.name = name;
            return ((Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap)(this)).GetDateOfNamesDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponse Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap.GetDatesOfNamesDay(Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest request) {
            return base.Channel.GetDatesOfNamesDay(request);
        }
        
        public Labb1WCF.Labb1_5Reff_2_service.ArrayOfString GetDatesOfNamesDay(string name) {
            Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest inValue = new Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest();
            inValue.Body = new Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequestBody();
            inValue.Body.name = name;
            Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponse retVal = ((Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap)(this)).GetDatesOfNamesDay(inValue);
            return retVal.Body.GetDatesOfNamesDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponse> Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap.GetDatesOfNamesDayAsync(Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest request) {
            return base.Channel.GetDatesOfNamesDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayResponse> GetDatesOfNamesDayAsync(string name) {
            Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest inValue = new Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequest();
            inValue.Body = new Labb1WCF.Labb1_5Reff_2_service.GetDatesOfNamesDayRequestBody();
            inValue.Body.name = name;
            return ((Labb1WCF.Labb1_5Reff_2_service.Labb1_5ServiceSoap)(this)).GetDatesOfNamesDayAsync(inValue);
        }
    }
}
