//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="ECUtbildning.Labb2_2AgeContract", ConfigurationName="IAgeContract")]
public interface IAgeContract
{
    
    [System.ServiceModel.OperationContractAttribute(Action="ECUtbildning.Labb2_2AgeContract/IAgeContract/GetYourAge", ReplyAction="ECUtbildning.Labb2_2AgeContract/IAgeContract/GetYourAgeResponse")]
    int GetYourAge(System.DateTime birthdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="ECUtbildning.Labb2_2AgeContract/IAgeContract/GetYourAge", ReplyAction="ECUtbildning.Labb2_2AgeContract/IAgeContract/GetYourAgeResponse")]
    System.Threading.Tasks.Task<int> GetYourAgeAsync(System.DateTime birthdate);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IAgeContractChannel : IAgeContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class AgeContractClient : System.ServiceModel.ClientBase<IAgeContract>, IAgeContract
{
    
    public AgeContractClient()
    {
    }
    
    public AgeContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public AgeContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AgeContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public AgeContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetYourAge(System.DateTime birthdate)
    {
        return base.Channel.GetYourAge(birthdate);
    }
    
    public System.Threading.Tasks.Task<int> GetYourAgeAsync(System.DateTime birthdate)
    {
        return base.Channel.GetYourAgeAsync(birthdate);
    }
}
