//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="ECUtbildning.Labb2_3Contract", ConfigurationName="IThousandDaysOld")]
public interface IThousandDaysOld
{
    
    [System.ServiceModel.OperationContractAttribute(Action="ECUtbildning.Labb2_3Contract/IThousandDaysOld/GetNextDateForThousandYearBirthday", ReplyAction="ECUtbildning.Labb2_3Contract/IThousandDaysOld/GetNextDateForThousandYearBirthdayR" +
        "esponse")]
    System.DateTime GetNextDateForThousandYearBirthday(string birthdate);
    
    [System.ServiceModel.OperationContractAttribute(Action="ECUtbildning.Labb2_3Contract/IThousandDaysOld/GetNextDateForThousandYearBirthday", ReplyAction="ECUtbildning.Labb2_3Contract/IThousandDaysOld/GetNextDateForThousandYearBirthdayR" +
        "esponse")]
    System.Threading.Tasks.Task<System.DateTime> GetNextDateForThousandYearBirthdayAsync(string birthdate);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IThousandDaysOldChannel : IThousandDaysOld, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ThousandDaysOldClient : System.ServiceModel.ClientBase<IThousandDaysOld>, IThousandDaysOld
{
    
    public ThousandDaysOldClient()
    {
    }
    
    public ThousandDaysOldClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ThousandDaysOldClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ThousandDaysOldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ThousandDaysOldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.DateTime GetNextDateForThousandYearBirthday(string birthdate)
    {
        return base.Channel.GetNextDateForThousandYearBirthday(birthdate);
    }
    
    public System.Threading.Tasks.Task<System.DateTime> GetNextDateForThousandYearBirthdayAsync(string birthdate)
    {
        return base.Channel.GetNextDateForThousandYearBirthdayAsync(birthdate);
    }
}
