//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="ECUtbildning.SelfService", ConfigurationName="ICalculateBMI")]
public interface ICalculateBMI
{
    
    [System.ServiceModel.OperationContractAttribute(Action="ECUtbildning.SelfService/ICalculateBMI/CalcBMI", ReplyAction="ECUtbildning.SelfService/ICalculateBMI/CalcBMIResponse")]
    double CalcBMI(int weight, int height);
    
    [System.ServiceModel.OperationContractAttribute(Action="ECUtbildning.SelfService/ICalculateBMI/CalcBMI", ReplyAction="ECUtbildning.SelfService/ICalculateBMI/CalcBMIResponse")]
    System.Threading.Tasks.Task<double> CalcBMIAsync(int weight, int height);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICalculateBMIChannel : ICalculateBMI, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateBMIClient : System.ServiceModel.ClientBase<ICalculateBMI>, ICalculateBMI
{
    
    public CalculateBMIClient()
    {
    }
    
    public CalculateBMIClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CalculateBMIClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateBMIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CalculateBMIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double CalcBMI(int weight, int height)
    {
        return base.Channel.CalcBMI(weight, height);
    }
    
    public System.Threading.Tasks.Task<double> CalcBMIAsync(int weight, int height)
    {
        return base.Channel.CalcBMIAsync(weight, height);
    }
}
