//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Labb1WCF.Labb1_4Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Labb1_4Reference.Labb1_4ServiceSoap")]
    public interface Labb1_4ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractNumber", ReplyAction="*")]
        double SubtractNumber(double x, double y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<double> SubtractNumberAsync(double x, double y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Labb1_4ServiceSoapChannel : Labb1WCF.Labb1_4Reference.Labb1_4ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Labb1_4ServiceSoapClient : System.ServiceModel.ClientBase<Labb1WCF.Labb1_4Reference.Labb1_4ServiceSoap>, Labb1WCF.Labb1_4Reference.Labb1_4ServiceSoap {
        
        public Labb1_4ServiceSoapClient() {
        }
        
        public Labb1_4ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Labb1_4ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_4ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Labb1_4ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double SubtractNumber(double x, double y) {
            return base.Channel.SubtractNumber(x, y);
        }
        
        public System.Threading.Tasks.Task<double> SubtractNumberAsync(double x, double y) {
            return base.Channel.SubtractNumberAsync(x, y);
        }
    }
}
